# Prebuilt MS image
FROM mcr.microsoft.com/playwright

# WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn

COPY . .

RUN yarn build

# Run the npm run test:e2e command to host the server and run the e2e tests
# CMD ["yarn", "start", "test-e2e"]
CMD yarn start & yarn test-e2e
# ENTRYPOINT [ "yarn test-e2e" ]